// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type LibraryUpdateState struct {
	TracksNumber  *int `json:"tracksNumber"`
	AlbumsNumber  *int `json:"albumsNumber"`
	ArtistsNumber *int `json:"artistsNumber"`
}

type Settings struct {
	LibraryPath            *string `json:"libraryPath"`
	CoversPreferredSource  *string `json:"coversPreferredSource"`
	DisableLibrarySettings *bool   `json:"disableLibrarySettings"`
	Version                *string `json:"version"`
}

type Variable struct {
	Key   *string `json:"key"`
	Value *string `json:"value"`
}
