version: '3'
services:
    server:
        build:
            context: .
            dockerfile: ./Dockerfile
        volumes:
            - ..:/app
        working_dir: /app
        ports:
            - 8888
        # Make container run indefinitely
        command: "tail -f /dev/null"
