version: '3'
services:
    client:
        build:
            context: .
            dockerfile: ./Dockerfile
        volumes:
            - ..:/app
        working_dir: /app
        ports:
            - 3000
        # Make container run indefinitely
        command: "tail -f /dev/null"
