name: Linter

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 20.x

      - name: Check backend code quality
        run : |
          cd server
          if [ "$(find . -iname '*.go' | xargs gofmt -l)" ]
          then
            find . -iname '*.go' | xargs gofmt -d
            exit 1
          fi

      - name: Install frontend dependencies
        run: cd client && yarn install

      - name: Check frontend code quality
        run: cd client && yarn lint
